/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkginterface;

/**
 *
 * @author Kat
 */
public class Counseling extends javax.swing.JFrame {

    /**
     * Creates new form Counseling
     */
    public Counseling() {
        initComponents();
        
        Update.setOpaque(false);
        Update.setContentAreaFilled(false);
        Update.setBorderPainted(false);
        
        Return.setOpaque(false);
        Return.setContentAreaFilled(false);
        Return.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IntakeDrop = new javax.swing.JComboBox();
        IntakeDrop1 = new javax.swing.JComboBox();
        IntakeDrop2 = new javax.swing.JComboBox();
        Update = new javax.swing.JButton();
        IntakeTF = new javax.swing.JTextField();
        MonthTF = new javax.swing.JTextField();
        OngoingTF = new javax.swing.JTextField();
        WalkinTF = new javax.swing.JTextField();
        Month = new javax.swing.JLabel();
        Return = new javax.swing.JButton();
        counseling_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 470));
        setMinimumSize(new java.awt.Dimension(600, 470));
        setPreferredSize(new java.awt.Dimension(600, 470));
        setSize(new java.awt.Dimension(600, 470));
        getContentPane().setLayout(null);

        IntakeDrop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Teri's Ongoing", "Emma's Ongoing", "Melva's Ongoing" }));
        IntakeDrop.setMaximumSize(new java.awt.Dimension(154, 27));
        getContentPane().add(IntakeDrop);
        IntakeDrop.setBounds(50, 170, 210, 27);

        IntakeDrop1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Teri's Walk-Ins", "Emma's Walk-Ins", "Melva's Walk-Ins" }));
        IntakeDrop1.setMaximumSize(new java.awt.Dimension(154, 27));
        getContentPane().add(IntakeDrop1);
        IntakeDrop1.setBounds(50, 226, 210, 27);

        IntakeDrop2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Teri's Intakes", "Emma's Intakes", "Melva's Intakes" }));
        IntakeDrop2.setMaximumSize(new java.awt.Dimension(154, 27));
        getContentPane().add(IntakeDrop2);
        IntakeDrop2.setBounds(50, 115, 210, 27);

        Update.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        Update.setForeground(new java.awt.Color(255, 102, 0));
        Update.setText("Update");
        getContentPane().add(Update);
        Update.setBounds(230, 330, 140, 40);
        getContentPane().add(IntakeTF);
        IntakeTF.setBounds(295, 113, 270, 30);
        getContentPane().add(MonthTF);
        MonthTF.setBounds(293, 279, 270, 30);
        MonthTF.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(OngoingTF);
        OngoingTF.setBounds(293, 168, 270, 30);
        getContentPane().add(WalkinTF);
        WalkinTF.setBounds(293, 224, 270, 30);

        Month.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Month.setForeground(new java.awt.Color(255, 102, 0));
        Month.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Month.setText("Month");
        getContentPane().add(Month);
        Month.setBounds(40, 280, 220, 30);
        getContentPane().add(Return);
        Return.setBounds(10, 390, 250, 50);

        counseling_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/ywca_counseling.png"))); // NOI18N
        getContentPane().add(counseling_bg);
        counseling_bg.setBounds(0, 0, 600, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Counseling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Counseling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Counseling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Counseling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Counseling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox IntakeDrop;
    private javax.swing.JComboBox IntakeDrop1;
    private javax.swing.JComboBox IntakeDrop2;
    private javax.swing.JTextField IntakeTF;
    private javax.swing.JLabel Month;
    private javax.swing.JTextField MonthTF;
    private javax.swing.JTextField OngoingTF;
    private javax.swing.JButton Return;
    private javax.swing.JButton Update;
    private javax.swing.JTextField WalkinTF;
    private javax.swing.JLabel counseling_bg;
    // End of variables declaration//GEN-END:variables
}
