/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkginterface;

/**
 *
 * @author Kat
 */
public class Main_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Main_Menu
     */
    public Main_Menu() {
        initComponents();

        SQL.setOpaque(false);
        SQL.setContentAreaFilled(false);
        SQL.setBorderPainted(false);

        reports.setOpaque(false);
        reports.setContentAreaFilled(false);
        reports.setBorderPainted(false);

        modify.setOpaque(false);
        modify.setContentAreaFilled(false);
        modify.setBorderPainted(false);

        logout.setOpaque(false);
        logout.setContentAreaFilled(false);
        logout.setBorderPainted(false);

        dbpath.setOpaque(false);
        dbpath.setContentAreaFilled(false);
        dbpath.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SQL = new javax.swing.JButton();
        reports = new javax.swing.JButton();
        modify = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        dbpath = new javax.swing.JButton();
        main_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("YWCA Database Main Menu");
        setMaximumSize(new java.awt.Dimension(600, 470));
        setMinimumSize(new java.awt.Dimension(600, 470));
        getContentPane().setLayout(null);

        SQL.setBackground(new java.awt.Color(255, 255, 255));
        SQL.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        SQL.setForeground(new java.awt.Color(255, 102, 51));
        SQL.setText("SQL");
        getContentPane().add(SQL);
        SQL.setBounds(134, 226, 330, 40);

        reports.setBackground(new java.awt.Color(255, 255, 255));
        reports.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        reports.setForeground(new java.awt.Color(255, 102, 51));
        reports.setText("Reports");
        reports.setToolTipText("");
        reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsActionPerformed(evt);
            }
        });
        getContentPane().add(reports);
        reports.setBounds(134, 113, 330, 40);

        modify.setBackground(new java.awt.Color(255, 255, 255));
        modify.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        modify.setForeground(new java.awt.Color(255, 102, 51));
        modify.setText("Modify");
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });
        getContentPane().add(modify);
        modify.setBounds(134, 169, 330, 40);

        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(20, 360, 90, 70);

        dbpath.setBackground(new java.awt.Color(255, 255, 255));
        dbpath.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        dbpath.setForeground(new java.awt.Color(255, 102, 51));
        dbpath.setText("Database Path");
        dbpath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbpathActionPerformed(evt);
            }
        });
        getContentPane().add(dbpath);
        dbpath.setBounds(134, 285, 330, 40);

        main_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/ywca_menu.png"))); // NOI18N
        getContentPane().add(main_bg);
        main_bg.setBounds(0, 0, 600, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsActionPerformed
        String[] args = null;
        Reports.main(args);// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_reportsActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        String[] args = null;
        Login.main(args);// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyActionPerformed
        String[] args = null;
        Update_Menu.main(args);// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_modifyActionPerformed

    private void dbpathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbpathActionPerformed
        String[] args = null;
        DBpath.main(args);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_dbpathActionPerformed

    public static void groupsMain() {
        String[] args = null;
        Groups.main(args);
    }

    public static void CounselingMain() {
        String[] args = null;
        Counseling.main(args);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SQL;
    private javax.swing.JButton dbpath;
    private javax.swing.JButton logout;
    private javax.swing.JLabel main_bg;
    private javax.swing.JButton modify;
    private javax.swing.JButton reports;
    // End of variables declaration//GEN-END:variables
}
